ABBREVIATIONS = {
        'Adriano Gill': 'AG',
        'Airton Casses': 'AS',
        'Alessandra Goncalves': 'AJ',
        'Alex Cortes': 'AM',
        'Alexandre SantosdaCosta': 'AC',
        'Elisa Prusch': 'AE',
        'Ana Lucia Rollo': 'AL',
        'Antonio Nascimento': 'AN',
        'Antonio Silveira': 'AD',
        'Armando Silva': 'AP',
        'Bia Alves': 'BA',
        'Chris Leal': 'CL',
        'Cicera Taran': 'CK',
        'Cristian Silva': 'CV',
        'Cristiano Mello': 'CM',
        'Daiani Fraga': 'DF',
        'Daniela Bedin': 'DB',
        'Dejair Souza': 'DC',
        'Dieferson Kievel': 'DK',
        'Diego Dal Sasso': 'DD',
        'Doli Paixão': 'DP',
        'Elói Martins': 'EM',
        'Fischer': 'EF',
        'Ester Marques': 'ET',
        'Fabiana Bastos': 'FB',
        'Fabiano Denck': 'FD',
        'Fabiano Gonçalves': 'FG',
        'Fran Bittencourt': 'FR',
        'Franklin Jacob': 'FJ',
        'Gabriel Garcia': 'GG',
        'Jaciane Dias': 'JD',
        'Jaqueline Souza': 'JA',
        'João Martins': 'JM',
        'Jose Eloy': 'JE',
        'Juliana Schneider': 'JB',
        'Cardoso Leandro': 'LC',
        'Luana Vargas': 'LP',
        'Lucas Zerbinato': 'LZ',
        'Oliveira Marcelo': 'MO',
        'Magda Moraes': 'MM',
        'Mari Nunes': 'MD',
        'Maurício dos Santos': 'MS',
        'Mayra Fontinele': 'MF',
        'Munique Becker': 'MB',
        'Nair Almeida': 'NM',
        'Nelton Ricardo da silva rodrigues': 'NR',
        'Nikolas Bastarrica': 'NB',
        'Nilo Martins': 'NA',
        'Orlando Pacheco': 'OP',
        'Otair Leite': 'OL',
        'Pamela Macedo': 'PC',
        'Brisch Brisch': 'PB',
        'Rafael Soto': 'RS',
        'Roberto Dias': 'RD',
        'Paulo Abarello': 'PA',
        'Lopes Paulo': 'PL',
        'Querlon Simões': 'QG',
        'Ricardo Mello': 'RM',
        'Rinaldo Jardim': 'RJ',
        'Rodrigo Behar Abreu': 'RB',
        'Silvana Cocaro':'SC',
        'Talma Flor': 'TR',
        'Tarciso Serafini': 'TS',
        'Valéria Antunes': 'VA',
        'Vitorhugo Serpa': 'VH',
        'William Otto': 'WO',
        'Yago Romano': 'YR'}