ABBREVIATIONS = {
    'Adriano Gill': 'AG',
    'Airton Casses': 'AS',
    'Alessandra Goncalves': 'AJ',
    'Alex Cortes': 'AM',
    'Alexandre Nunes dos Santos': 'NS',
    'Alexandre SantosdaCosta': 'AC',
    'Elisa Prusch': 'AE',
    'Ana Lucia Rollo': 'AL',
    'Andressa de Souza Lopes': 'AR',
    'Antonio Nascimento': 'AN',
    'Antonio Silveira': 'AD',
    'Armando Silva': 'AP',
    'Bia Alves': 'BA',
    'Chris Leal': 'CL',
    'Cicera Taran': 'CK',
    'Cristian Silva': 'CV',
    'Cristiano Mello': 'CM',
    'Daiani Fraga': 'DF',
    'Daniela Bedin': 'DB',
    'Dejair Souza': 'DC',
    'Denir Angelo Bottega': 'DA',
    'Dieferson Kievel': 'DK',
    'Diego Dal Sasso': 'DD',
    'Doli Paixão': 'DP',
    'Douglas Balsemao Hernandez': 'DH',
    'Elói Martins': 'EM',
    'Fischer': 'EF',
    'Eliana Frota de Avila': 'EA',
    'Ester Marques': 'ET',
    'Fabiana Bastos': 'FB',
    'Fabiano Denck': 'FD',
    'Fabiano Gonçalves': 'FG',
    'Fernando Weber': 'FW',
    'Fran Bittencourt': 'FC',
    'Franklin Jacob': 'FJ',
    'Gabriel Garcia': 'GG',
    'Jaciane Dias': 'JD',
    'Jaqueline Souza': 'JA',
    'Jeferson Flores': 'JF',
    'João Martins': 'JM',
    'Jose Eloy': 'JE',
    'Juliana Schneider': 'JB',
    'Julio Godoy': 'JG',
    'Kelvi Adriano Dias': 'KD',
    'Cardoso Leandro': 'LC',
    'Luana Vargas': 'LP',
    'Lucas Zerbinato': 'LZ',
    'Oliveira Marcelo': 'MO',
    'Magda Moraes': 'MM',
    'Maicon Ryan Lauermann': 'MR',
    'Mari Nunes': 'MD',
    'Mário Sérgio Osorio Belmonte': 'MA',
    'Maurício dos Santos': 'MS',
    'Mayra Fontinele': 'MF',
    'Munique Becker': 'MB',
    'Nair Almeida': 'NM',
    'Nelton Ricardo da silva rodrigues': 'NR',
    'Nikolas Bastarrica': 'NB',
    'Nilo Martins': 'NA',
    'Orlando Pacheco': 'OP',
    'Otair Leite': 'OL',
    'Pamela Macedo': 'PC',
    'Brisch Brisch': 'PB',
    'Rafael Soto': 'RS',
    'Roberto Dias': 'RD',
    'Paulo Abarello': 'PA',
    'Paulo César da Silva': 'PC',
    'Lopes Paulo': 'PL',
    'Querlon Simões': 'QG',
    'Ricardo Mello': 'RM',
    'Rinaldo Jardim': 'RJ',
    'Rodrigo Behar Abreu': 'RB',
    'Sandro Chaves Brum Leal': 'SL',
    'Sérgio Pedroso da Silva': 'SP',
    'Silvana Cocaro': 'SC',
    'Silvana de Lourdes Guimarães Barcellos': 'SB',
    'Solaine da Cunha Aquino': 'SA',
    'Talma Flor': 'TR',
    'Tarciso Serafini': 'TS',
    'Thales Zanella': 'TZ',
    'Valéria Antunes': 'VA',
    'Verônica Agostini': 'VE',
    'Vani Dila Mônaco': 'VM',
    'Vitorhugo Serpa': 'VH',
    'William Otto': 'WO',
    'Yago Romano': 'YR'}
