PDV_TYPES = {
    'Atmosfera': 'PDV Estoque',
    'Medplex Santana': 'PDV Estoque',
    'NY205': 'PDV Estoque',
    'Pirata Farnese': 'PDV Lançamento',
    'Prime Altos do Germânia': 'PDV Estoque',
    'Prime Menino Deus': 'PDV Estoque',
    'Prime Wallig': 'PDV Lançamento',
    'Prime Wish': 'PDV Estoque',
    'Sede Seller': 'Online',
    'The Arch': 'PDV Estoque',
    'The Park': 'PDV Lançamento',
    'Vintage Senior Residence': 'PDV Estoque',
    'Yoo Moinhos': 'PDV Estoque',
    'Zaffari Cabral': 'PDV Estoque',
    'Chat Manhã': 'Online',
    'Chat Tarde': 'Online',
    'Chat Noite': 'Online',
    '8652 Manhã': 'Telefone',
    '8652 Tarde': 'Telefone'
}